services:
  line-provider:
    build:
      context: ../..
      dockerfile: envs/dev/Dockerfile
    ports:
      - '8000:8000'
    env_file:
      - ../../.env
    volumes:
      - ../../app:/app
    restart: unless-stopped
    networks:
      - betting

  redis:
    image: mirror.gcr.io/redis:7.2.4
    restart: unless-stopped
    volumes:
      - redis:/root/redis
      - redis:/usr/local/etc/redis/redis.conf
    networks:
      - betting
    

volumes:
  redis:

networks:
  betting:
    external: true
